### ISSUE TITLE
[2019-02-28] vscode中开发vue的最佳实践

### ISSUE THREAD

**Issue by coppyC** [coppyC/blog#1]
# 序
vue 在去年star数量超越了react ，一举成为前端框架中star数量最多的框架  

而vscode又是目前star数最多的开源编辑器   

这两个东西碰撞后会擦出什么火花 

# 目录
* [安装 vetur](#t1)
* [添加 .vue 后缀](#t2)
* [添加 jsconfig.json](#t3)
* [使用 jsdoc 注释](#t4)
* [使用 typescript](#t5)
* [仍有提示的缺陷](#t6)
* [总结及其它小技巧](#t7)

<h1 id="t1">安装 vetur</h1>

要想在 vscode 获得 vue 文件的语法高亮以及提示，需要在vscode中安装 vetur 插件。

安装完后，打开你的vue项目，正常情况下，就会拥有语法高亮以及智能提示了。

## 为什么我只有高亮，没有提示？
安装后可能会出现只有高亮，没有提示的情况，这个是正常的。  
因为vetur主要是提供高亮，提示功能需要与vue的npm包进行协作，才能工作。  

如果没有提示，请确保你已经安装了相关依赖  
如果没有安装依赖 ，请执行 ` npm i `  

## 为什么我在mpvue开发中没有等到友好的vue提示
如果你使用mpvue开发小程序，你可能会发现提示会出这样现错误，this并不是指向vue的实例，
这是因为mpvue官方的模版中没有安装vue，导致不能正确提示，
这也就是mpvue项目中，没有提示的一个原因

知道了原因，问题就很好解决了，执行命令 `npm i vue --save-dev`

<h1 id="t2">添加 .vue 后缀</h1>

```js
// bad
import Calendar from './Calendar'

// good
import Calendar from './Calendar.vue'
```
## 为什么要这么做？
在标准的js或ts语法中，只能导入js或ts，
如果要导入其它文件，是需要加后缀的，不加后缀的是默认为js/ts。

而不加后缀依然可以正确运行，是因为，这是webpack帮你做了事，但vscode却不会帮你这么做

## 加后缀后有什么好处？
* vue文件导航: 按住`ctrl` + 鼠标点击，可以跳转到对应文件  
![vue文件导航](https://user-images.githubusercontent.com/25004510/53489397-0ef22380-3acc-11e9-80a5-23a868799d61.gif)

* 组件提示: 在template中按`<`后可以出现vue组件的提示  
![组件提示](https://user-images.githubusercontent.com/25004510/53489626-9fc8ff00-3acc-11e9-8eab-672dc6627062.png)

* props 提示  
![props](https://user-images.githubusercontent.com/25004510/53489717-d99a0580-3acc-11e9-9812-145412817d9a.png)

## 加了后缀依然不能拥有上述能力
上述功能只对相对路径导入有效，如果使用了类似 '@/xxx' 的路径，可以添加 jsconfig.json 文件

<h1 id="t3">添加 jsconfig.json / tsconfig.json 文件</h1>

注意！！jsconfig.json 为vscode特有，当然，也不排除其它编辑器借鉴，所以一般只有在vscode中才能工作。

关于jsconfig.json的更多信息，可以查看 <a href="https://code.visualstudio.com/docs/languages/jsconfig" target="_blank">vscode文档相关说明</a>。

## 如何添加
在项目的根目录下新建 jsconfig.json (ts项目请使用tsconfig.json)，然后粘贴以下代码
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
  },
  "include": [
    "./src/**/*.vue",
    "./src/**/*.js",
  ],
  "exclude": [
    "node_modules"
  ]
}
```
## 这样做有什么好处？
* 对于'@/xxxx'导入的vue文件可以正常进行跳转和提示
* js代码检查，对没有声明的变量，对象中没有的属性进行报错提示（需要在compilerOptions添加"checkJs": true开启）
* 可以对整个项目的 js/vue 文件进行关联，文件提示更全，自动导入文件（导入的vue文件会自动加后缀）  

![使用前](https://user-images.githubusercontent.com/25004510/53491024-3ba83a00-3ad0-11e9-983f-4ef79806e07a.png)   
使用前，文件提示很迷👆🏻    
使用后👇🏻   
![使用后](https://user-images.githubusercontent.com/25004510/53491028-3e0a9400-3ad0-11e9-993d-f354f6e9e0b9.png)

## 如果使用后，vue文件提示卡顿
<a href="https://github.com/vuejs/vetur/issues/547" target="_blank">相关issue #547</a>  
<a href="https://github.com/vuejs/vetur/issues/948" target="_blank">相关issue #948</a>

我之前在我的旧比记本（一台三代i5的linux）上，也出现过相同情况，而现在用的是一台 i7 8700的机器，并没有出现卡顿情况，而上述issue，一个是出现在windows平台，一个是在mac平台，我是出现在linux平台，三个平台都出现，应该与平台无关。所以我怀疑应该是消耗大量cpu计算，导致提示缓慢。
<a href="https://github.com/vuejs/vetur/issues/913" target="_blank">相关issue #913</a>

## 卡顿解决方案
可以在jsconfig.json下的compilerOptions 添加 `"moduleResolution": "classic"`选项
```json
{
  "compilerOptions": {
    "moduleResolution": "classic"
  }
}
```
@thanks [tartinesKiller](https://github.com/vuejs/vetur/issues/547#issuecomment-425731662)

如果这么设置之后还卡顿，现在就只有下面几条路可以走  
1. 删除jsconfig.json，等待vetur解决后再用
2. 忍受卡顿，等待vetur解决
3. 卸载vscode，等待vetur解决后再下载
4. 转行，等待vetur解决后再打代码
5. 冲值购买新电脑

<h1 id="t4">使用 jsdoc 注释</h1>

很多时候，由于js弱类型的特点，让vscode在很多时候不能很好地推断变量的类型，
像这种情况
```js
function xxx(array) {
  // 这个array是个什么，string？number？Array？
}
```
一直在友好的提示环境下呆久了，一但没有了提示，就会浑身难受

这个时候，一个比较简单的方法让vsc可以推断其类型的方法就是，为参数添加默认值，像这样
```js
function xxx(array=[]) {
  // vscode 会认为array是一个数组，并提供相关提示
}
```
如此一来，vsc就可以推断出arrary是一个数组，你甚至可以这么写`array=['']`，让vsc推断出它是一个`number[]`，但因为这是es6的默认参数语法，所以如果你为了获得提示而这么写，它会一个负作用，当没有传参数进来，这个默认值会生效，一般情况下，这会很有用，可以防止没有带参数过来而在某些情况下报错，但有的时候，我们不想要这个默认值，这就有点棘手了。而且在某些情况下，即使写了默认值，vsc依然不能推断参数的类型，像在vue methods中的函数。这种情况下，我们可以使用 jsdoc 来进行注释

## jsdoc 是什么？
jsdoc 是js一种很流行的注释风格，可以通过jsdoc来生成js的api文档

在vscode中，自带对jsdoc的支持，可以增强对js的提示，像前面的函数，可以这么写，来增强提示
```js
/**
 * @param {number[]} array
 */
function xxx(array) {
  // 通过上面的注释，vscode就知道 array 是一个包含number类型的数组
}
```
更多jsdoc在vscode的写法和支持程度，可以看[这里](#https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript)，这里就不再赘述

如果大家有兴趣，欢迎留言，我会出一期在vscode里面写jsdoc的各种情况

## jsdoc 过于繁琐
当你过分使用jsdoc时，你可能会觉得jsdoc繁琐。

嗯。。。你是对的。。。

jsdoc的书写确实是过于繁琐，一个jsdoc会占很多行代码，十分影响代码阅读，

如果你过分依赖代码提示，不妨试试使用typescript

<h1 id="t5">使用 typescript</h1>

很多时候，我推荐别人用ts，他们是拒绝的，因为他们觉得，ts束缚了他们，让js变得不那么灵活。实际上，他们是对的，因为很多在js通过的语法，在ts都不能通过。但ts已经经过几年的发展，ts似乎已经成为类似eslint一样辅助js的东西，即使ts会报错，但依旧会编译成js，依旧可以运行，不过前提是你的js代码没有错。

## 什么是ts （typescript）?
typescript 是微软推出的js超集，江湖人称强类型版js，他类和C#有着十分相近的，毕竟是同一个人设计的，如果你喜欢强类型语言，又不得不写js，那ts可能是你最好的归宿。

随着js应用越来越复杂，一个友好的提示显得会十分重要，vscode本身就是在electron的基础上，用ts写的，对ts也提供了开箱及用的友好支持。

## 为什么不选择用 flow.js?
flow.js 是facebook为了做类型检查设计的，目前和ts解决的是同一个问题。目前facebook的react是用flow.js来做检查，vue2.x也是用flow.js。 

而选择ts只是因为ts越来越流行，社区热度也比flow.js高很多，开发体验上可能也比flow.js好(为什么是可能，因为我也没用过flow.js)，而且react 17 和 vue3 都将采用ts重写，所以flow.js会成为弃婴。

## 在vue中使用ts
想在vue中使用ts，如果是新建项目，直接用 [vue cli3 (@vue/cli)](https://cli.vuejs.org/zh/)  来安装，提供的typescript选项，无需自己折腾，就可以创建vue-ts应用

然后在函数中就可以通过类型声明来增强提示了
```ts
function xxx(array:number[]) {
  // array 是一个包含number类型的数组
}
```
这样在js中很难做到的提示，现在在ts可以轻松做到

![image](https://user-images.githubusercontent.com/25004510/53545070-3516d280-3b63-11e9-9c63-24e261368646.png)

现在vscode可以知道list数组是一个对象数组，每个对象都有x和y两个属性。 nice!

## 风格的选择
目录ts in vue有3种风格写法

1. 原风格
```js
// 仅支持在vue文件中写
export default {
  data() {
    return {
      //....
    }
  },
  methods: {
    //....
  }
}
```
2. 使用 `Vue.extend`
```ts
// 可以在非 .vue 文件获得友好提示
export default Vue.extend({
  data() {
    return {
      //....
    }
  },
  methods: {
    //....
  }
}）
```
3. 使用类风格

类风格并不是ts版本特有的，es6开始就有类语法了,
只不过在ts中对类的支持更强大罢了。
但是你如果在vue的js版本使用类风格，可能会气出血。
``` ts
import { Component, Prop, Vue } from 'vue-property-decorator'

@Component(
  compoments: { /** .... */ }
)
export default class extends Vue {
  x = 1
  y = 'string'

  @Prop() msg!: string

  changeX() {
    this.x = 2
  }
}
```
类风格的写法可能会和以前的写法有很大的区别，使用了很多装饰器，先说说优点

## 类风格优点
类风格的vue更加简洁，更有逼格，合理使用可以劝退其他想学习前端的同学，他有如下优点：
* （优雅）因为类的语法糖，不需要逗号分隔，不像js对象一样，需要在每个属性之间用`逗号,`隔开
* （清晰）有特殊功能的使用了 装饰器 修饰，一眼扫过去很容易知道这个是干嘛的，特别是@Emit，在对象版的vue中，不能清晰看到这个组件有什么事件，因为对象版的是使用`this.$emit()`混在各各地方中
* （简洁）对象版中的data是一个函数，需要return一个对象出来，过于繁琐的写法，现在不用了，直接在类中声明，像上面的例子声明了 `x` 和 `y` 变量，十分简洁。而且由于使用了装饰器，不用再使用 methods: {} 这些，减少了代码的缩进和行数

很多时候，一种风格的转换，因为不习惯，只会看到它的缺点，然后就说得一无是处，其实不可否认，这种写法也有它的优点存在。

尽管我这么说，可还是有些人不喜欢，没事，我还为你开了一条路，点击[这里](#t6)，然后大声嘲笑类风格的vue

## 部分装饰器用法

用 `@Component` 来声明组件，经过探索发现，如果用不到里面的选项，可以省略这个不写

用 `@Prop` 来声明props
官方的写法是这样的，有些复杂和冗余
```ts
@Component
export default class YourComponent extends Vue {
  @Prop(Number) readonly propA!: number
  @Prop({ default: 'default value' }) readonly propB!: string
  @Prop([String, Boolean]) readonly propC!: string | boolean
}
```
本着探索和偷懒的精神，我发现上面利用ts类的特性这么简tou写lan
```ts
export default class YourComponent extends Vue {
  @Prop() propA!: number
  @Prop() propB = 'default value'
  @Prop() propC!: string | boolean
}
```
需要类型判断的，就 prop `!:` 类型，需要默认值的，就直接 prop `=` 默认值，让ts自己推断类型，这样写起来就比对象风格简洁很多

更多vue装饰器及用法可以看[官方文档](https://github.com/kaorun343/vue-property-decorator)

更多偷懒的写法可能就要你自己去探索了，因为我接下来要讲一件沉重的事情，导致类风格的探索到此结束

## 类风格缺点
上面的代码看上去是那么美好，不是吗？不是的。或许在别的编辑器下是，但在vscode中并没有那么美。

以上类风格在写`script`的时候还很棒，有十分完美的提示，这利益于ts的提示，但在写`template`可能就不那么舒服了

让我们先来看看对象风格的提示
``` js
export default {
  data: {
    x: 1,
    y: 2,
  },
  props: {
    msg: String
  }
}
```
![image](https://user-images.githubusercontent.com/25004510/53545686-3cd77680-3b65-11e9-815a-7e31eb57540a.png)

nice！

再来看看类风格的提示
``` ts
export default class extends Vue {
  x = 1
  y = 2
  @Prop() msg!: string
}
```
![screen shot 2019-02-28 at 2 39 52 pm](https://user-images.githubusercontent.com/25004510/53546218-bcb21080-3b66-11e9-9345-fa931c078920.png)

这。。。似乎不太妙了。。 打不到这种属性的提示
![property](https://code.visualstudio.com/assets/docs/editor/intellisense/Property_16x.svg)，
只剩下这些打过的单词提示
![property](https://code.visualstudio.com/assets/docs/editor/intellisense/String_16x.svg)，

而且如果你通过`@Component`来载入组件，那么也得不到前面说到的这类提示
![组件提示](https://user-images.githubusercontent.com/25004510/53489626-9fc8ff00-3acc-11e9-8eab-672dc6627062.png)

总之就是，在`template`中失去所有关于`script`内容的提示

但如果你真的很喜欢类风格的话，顶多也就是失去`template`的提示罢了

缺点小结
* `template` 中提示不友好 ( vetur出来背锅 )
* 如果有过多props，需要重复写`@Prop()`，繁琐

<h1 id="t6">仍有提示的缺陷</h1>

`script`部分的提示已经近乎完美，主要还是`template`存在缺陷

![image](https://user-images.githubusercontent.com/25004510/53547725-bcb40f80-3b6a-11e9-922c-41bd5a577cc1.png)

从图中可以看出，在template对data等的提示，只能进行浅层面的提示，即使我在data中对list写了ts类型，依然不行

此外，函数的调用，只能提示函数名，参数怎么填写也提示不了

另外，`template` 和 `style` 部分不能联动，表现为`class=""`不能出现style部分的css类名提示，不知道各路神仙有什么办法。
其它位置的css文件的提示，可以通过安装 `IntelliSense for CSS, SCSS class names in HTML, Slim and SCSS` 插件提供帮助。

<h1 id="t7">总结及其它小技巧</h1>

1. 有了vetur，vue在vscode中的开发体验已经是十分友好了
2. 通过 .vue 后缀可以进行跳转
3. 配置 jsconfig.json 让开发更加舒适
4. 提示不够，jsdoc 来凑，如果不行，再加点ts
5. 关于ts的风格，我推荐是使用对象写法，因为用类总有一种不是在写vue的感觉，和vue社区格格不入，而用对象的写法会接近以前的风格，减少迁移到ts成本，同时也能获得模版代码友好的提示，当然，如果你不介意模版代码失去提示的话，你可以使用类风格，反正模版的提示本来也不是很强，再说了，还有word提示，出现拼写错误应该还不至于
7. 因为 vue 官方最开始只支持js，对ts的支持比较晚，这使得ts版本的vue看起来并不是很强势。在支持ts后，写了很多 types 文件，使得js版本的vue 拥有着十分强大的提示，当我第一次看到他的this可以正确提示的时候，我觉得这很crazy. 
8. 使用ts版本的vue可能不会给你开发体验带来质的飞跃，真正的ts开发体验，应该可以检查出所有可能的错误，进行精准的推断，但这些在ts版本的vue中都没有（vetur出来背锅），毕竟vue主要还是js用户居多，ts用户或许几乎没有吧。反观与ts深度融合的 angular ，则可以在html中做到这些精准推断：[效果](https://angular.cn/guide/language-service)，只能看看vue3用ts重写后会不会好一些，不过我觉得问题关键还是在vetur，现在有types的vue对用户来说，和ts没有区别。就目前说来，我觉得vue的ts版本并没有
9. *.d.ts并不是ts特有，在vscode中，可以通过写 *.d.ts 来增强提示。像`this.$http.xxx`这些挂在根元素的，可以通过 .d.ts 来产生提示， 详见[官方教程](https://vuejs.bootcss.com/v2/guide/typescript.html#%E5%A2%9E%E5%BC%BA%E7%B1%BB%E5%9E%8B%E4%BB%A5%E9%85%8D%E5%90%88%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8)，这在使用插件或mpvue中会很有用,同时也可以给 `$store` 增强类型
10. 在使用vuex时，如果不想为 `$store` 编写 .d.ts, 可以不使用`$store`，在需要用到store时，通过`import` 引入 然后给计算属性计算一下，这样就可以偷懒，同时获得store里面的提示。

# 不能出现在目录的后记
有的人可能会问，既然你这么喜欢ts，怎么不去用angular啊？
1. 我很喜欢vue那种，html,css,js全写在一个文件的风格，然后利用组件来进行代码分割。这样代码看起来更加紧凑，有上下文，而且组件迁移起来也方便，不会出现过多层级目录，更重要的是，编辑一个组件的时候，不用打开几个文件，然后来回切换
2. angular 比较重，虽然提供了一套解决方案(全家桶)，但是因为太完美，导致社区不是很活跃。我还是比较喜欢轻一点的框架，然后根据自己的喜好，组装不同的社区部件，甚至自己编写部件，打造很贴合自己使用的框架。

所以欢迎收看下期节目《为什么我从vue转到react了》

喜欢的同学可以在右上角点个 `watch` 来订阅，下次更新了就会通知你了哦。

![watch](https://user-images.githubusercontent.com/25004510/53551410-3997b700-3b74-11e9-877f-0f1516d528fb.gif)

有什么疑问欢迎在下面评论发言，但不要提issue哦。

**Comment by xqdd** [comment]
sofa

**Comment by lisiur** [comment]
总结的很好

**Comment by coppyC** [comment]
@lisiur thanks for reading

**Comment by weijiqiang1024** [comment]
能问一下编辑器用的什么字体和主题吗

**Comment by xqdd** [comment]
![image](https://user-images.githubusercontent.com/20871761/58888513-16077e00-871a-11e9-88f7-57fa53ca63f1.png)
欢迎查看我的下期节目《为什么我从React转Vue了》

**Comment by coppyC** [comment]
> 能问一下编辑器用的什么字体和主题吗

@weijiqiang1024 
主题是 One Dark Pro
字体使用的是默认的
其它像行高之类的设置在这里 https://gist.github.com/coppyC/a9043044954519606e122397e159a008#file-settings-json

**Comment by weijiqiang1024** [comment]
3Q @coppyC

**Comment by wendell0316** [comment]
你好，请问下为什么vue中有的文件中的函数不能提示，转到定义提示没有任何定义，而有的文件又正常工作

**Comment by coppyC** [comment]
@wendell0316 
这个问题我也经常遇到，特别是在写 mpvue 的时候，即使装了 `npm i vue`也是
听你这么一说，我刚才去研究了一下，找到了原因
```js
export default {
  data() {
    return {
      a: 1,
      b: 2,
    }
  },
  methods: {
    dosomething() {
      
    }
  },
}
```
像上面这个就可以正常提示
而像下面这个，多了个 onShow 方法就不行
```js
export default {
  data() {
    return {
      a: 1,
      b: 2,
    }
  },
  methods: {
    dosomething() {
                 
    }
  },
  onShow() {

  } 
}
```
原因是 onShow（这个不是写在 methods 里面的） 这个方法不是 vue 合法选项(vue 选项应该是 data、methods、created 这些)、vscode 的提示基于 typescript，而 vue 的typescript 描述文件比较复杂，出了一些差错就会解析失败，然后出不了提示。

而在 mpvue 这类拓展框架中，拓展了 vue 的原型，有 onLoad、onShow 之类的拓展也很正常，但不符合 vue 的选项。如果你是用 typescript 的话可以看一下[这里](https://vuejs.bootcss.com/v2/guide/typescript.html#%E5%A2%9E%E5%BC%BA%E7%B1%BB%E5%9E%8B%E4%BB%A5%E9%85%8D%E5%90%88%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8)怎么拓展原型和选项。

有空我写一篇博客详细讲一下 js/ts 怎么拓展vue 的原型和选项。

**Comment by wencaizhang** [comment]
有个关于 `jsconfig.json` 的问题请教一下。

jsconfig.json 在识别 alias 时，除非在路径中指明了后缀，否则默认将文件都当作 js 文件处理。

所以在 import vue 模块时如果不写 `.vue` 后缀，就无法识别正确路径。

但是习惯上 vue 文件和 js 文件的后缀都会被省略掉。

例如下面代码

```js
// 省略了 .vue 后缀，无法识别
import PageHeader from "@/components/PageHeader";
// 指明了 .vue 后缀，可以识别
import PageFooter from "@/components/PageFooter.vue";
// 省略了 .js 后缀，默认当作 js 处理
import util from "@/utils/util";
```

我的 `jsconfig.json` 代码如下：

```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
        "@/*": ["src/*"],
    }
  },
  "include": [
    "./src/**/*.vue",
    "./src/**/*.js",
  ],
  "exclude": [
    "node_modules"
  ]
}
```

请问您遇到这个问题了吗，又是如何处理呢？

**Comment by coppyC** [comment]
@weijiqiang1024 

我这边都是加上了后缀，虽然很多示例都是不打后缀，但是vetur里面是推荐带上.vue后缀的写法

> You need to add .vue extension when importing SFC.

原文： https://vuejs.github.io/vetur/FAQ.html#vetur-cannot-recognize-my-vue-component-import-such-as-import-comp-from-comp

关于路径我不是手打的，我是利用vscode提示来自动导入（上文中也有提到），十分好用，导入的vue路径也会自动带上 .vue 后缀，js文件则不会

如果是旧项目，也不用大费周折去改，在需要跳转或提示的时候，再加上后缀就好了，另外，加上后缀可以更好得和js文件区分开。

如果你实在不想加后缀，可以试试 webstorm

**Comment by zisheng-ai** [comment]
vue-peek

**Comment by d1y** [comment]
emmm, 大神我怎么看你第一张截图都感觉是`atom`🙂

**Comment by coppyC** [comment]
@d1y 这都被你发现了，始于 atom 的颜值，终于其卡顿。
最后，给我的 vscode 用了 atom 的配色主题 one dark pro
所以，这是拥有atom颜值，如假包换的 vscode.

**Comment by zisheng-ai** [comment]
始于Atom的颜值，终于Vscode的崛起

**Comment by Tritty** [comment]
@coppyC ,jsconfig我也配置了，但是我发现无法自动导入 .vue文件定义的组件，但是可以导入.js定义的组件。
比如有两个组件分别定义在` ./src/component/business/BaseList/index.js`和`src/components/business/MultiCascader/index.vue`中，我在某个index.vue文件中输入`BaseList`就会提示自动导入，但是输入`MultiCascader`就不会有任何提示。
请问你有遇到这个问题吗？是如何解决的呢？

**Comment by coppyC** [comment]
@Tritty 
如果没有记错的话，要打index才有那个vue文件名提示，vscode对vue的自动导入支持没有js好，把vue文件命名改成 src/components/business/MultiCascader.vue试试

**Comment by Tritty** [comment]
@coppyC   文件名为组件名.vue的组件也无法自动导入，连组件名的智能提示都没有

![image](https://user-images.githubusercontent.com/11994083/72033654-e59a4a80-32cd-11ea-9a25-0ead4187a094.png)

**Comment by coppyC** [comment]
@Tritty 
很久没搞vue了，刚又研究了一下，vscode 对 vue 的自动导入除了jsconfig.json外，还需要满足几个条件

1. 首先，在components 里面直接打是没有提示的，我知道你是要打的 es6 的属性同名简写，但vscode 不知道，它以为你要打的是属性名，属性名是不会提示的，这就和变量定义一样，起什么名字都没有对错之分。这点 vscode 是没有考虑好，所以只能委屈你**在 export default 上面打提示出来**，自动导入。
2. vscode 对vue的自动导入确实没有js/ts支持的好，可能是 vetur 处理 vue 文件，然后通知vscode这个是js文件。**所以这个文件，必须在 vscode 启动后打开过，才会出现在自动导入的提示中**。因为是vue 文件，所以即使配置 jsconfig，vscode 的ts引擎也不会主动扫描它(不过神奇的是，同级目录下的vue 文件不用打开过也能有提示。) 打不出来的话，可以先 `ctrl+p` 打开文件，然后`ctrl + tab`切回来继续打。

就第2点来说，这个功能对vue文件有点鸡肋。而且在vue文件中导入的路径还没有 以 `@/xx` 开头，重构起来也麻烦

**Comment by fidding** [comment]
import需加上.vue后缀，并且配置完需要重启vscode！！！

**Comment by qianzai** [comment]
请问，我按照你说的安装 vetur，添加 jsconfig.json导入组件的时候，然而还是什么提示都没有

**Comment by coppyC** [comment]
这个帖是2年前写的，有些内容可能已经过时了，现在vetur 的提示有没有改进我也不太清楚。
主要是我也很久不用vue了，有很多问题我可能答不上来。

建议折腾不过来的同学直接使用 webstrom 开发vue。号称最聪明的 js ide一定不会让你失望。
（虽然我没用过，主要是穷。说着说着就哭了出来....）

**Comment by millievn** [comment]
> 这个帖是2年前写的，有些内容可能已经过时了，现在vetur 的提示有没有改进我也不太清楚。
> 主要是我也很久不用vue了，有很多问题我可能答不上来。
> 
> 建议折腾不过来的同学直接使用 webstrom 开发vue。号称最聪明的 js ide一定不会让你失望。
> （虽然我没用过，主要是穷。说着说着就哭了出来....）

any news?
