### ISSUE TITLE
[2019-11-06] 如何使用小程序云开发白嫖一个图床 (小程序设置css背景图最佳实践)

### ISSUE THREAD

**Issue by coppyC** [coppyC/blog#14]
在css设置本地图片的背景图时，经常是走不通的，会看到这么一个报错

```
Can not fetch local image resources in app.wxss by WXSS. Pleause use web images, base64 or <image/>，Reference documents: https://developers.weixin.qq.com/miniprogram/dev/qa.html#%E6%9C%AC%E5%9C%B0%E8%B5%84%E6%BA%90%E6%97%A0%E6%B3%95%E9%80%9A%E8%BF%87-wxss-%E8%8E%B7%E5%8F%96
```
翻译一下
```
本地资源图片无法通过WXSS获取，可以使用网络图片，或者 base64，或者使用<image/>标签，文档链接：https://developers.weixin.qq.com/miniprogram/dev/qa.html#%E6%9C%AC%E5%9C%B0%E8%B5%84%E6%BA%90%E6%97%A0%E6%B3%95%E9%80%9A%E8%BF%87-wxss-%E8%8E%B7%E5%8F%96
```

以前还好一点，现在这个文档链接打开直接404。。。。

说说目前主流的几种方法：

1. 使用<image/>，然后通过   `position: relative;` 和 `position: absolute;` 来伪装成背景图。
这种方案有个缺点，就是写起来比较繁琐，相对css的方案较难复用。

2. 使用base64替代本地图片：
这种方案发动成本相对较小，麻烦在每次都需要将图片转换成 base64，而且污染代码 （如果不是原生开发的小程序倒是没有这些问题）。还有一个问题，就是图片还会变大 1/3。一般来说，做背景图的图片都不会太小，而前端代码体积的瓶颈一般就是图片，有点得不尝失。不过好在有Google的开源压缩网站[squoosh](https://squoosh.app/)，可以压缩图片，我刚刚还上传了一张 80k+的png图片，压缩后变4K jpg，质量只有一点变差，对手机来说难以察觉。

3. 使用web images：
就是把图片上传到云服务器，然后使用 远程的图片链接替代本地图片链接。
这个方案应该是目前最好的，但也有一个致命的缺点，就是开发的时候，不一定有服务器啊。就算有临时服务器，迁移到正式服务器上也有成本，还有服务器网速给不给力等问题。

是的，今天，我们就用小程序的**云开发**来白嫖云开发服务器做**图床**，解决方案 3 的唯一缺点 

1. 开通云开发
首先，打开小程序开发工具，打开你正在开发的小程序，点击 `Cloud Base` 即云开发 按钮。
注意，不能用测试的 appid，只有正式申请的小程序才能开通云开发。
![image](https://user-images.githubusercontent.com/25004510/68261857-54fc7f80-007c-11ea-8544-7000035e4064.png) 

点击开通按钮，开通后的云开发会与本小程序绑定
![image](https://user-images.githubusercontent.com/25004510/68261895-752c3e80-007c-11ea-8f79-21574763d2dd.png)

然后就是创建一个环境，命个名就好了，我这里用的是 cdn 这样的命名，通俗易懂。

2. 上传图片到云开发
点击 `Storage` 存储  按钮，切换到存储界面
![image](https://user-images.githubusercontent.com/25004510/68262247-a6f1d500-007d-11ea-929e-649c6eebf494.png)

然后 再点击`Upload File`上传按钮，选择你要上传的图片，可也可以创建文件夹来整理你的文件
![image](https://user-images.githubusercontent.com/25004510/68262280-bf61ef80-007d-11ea-8a27-53c83fb5c366.png)

3. 获取图片链接
那我们上传的图片在哪里呢?
这个时候，右键点击查看详情(或点击文件名)，右侧会出来一个抽屉模态框。
![image](https://user-images.githubusercontent.com/25004510/68262477-5af36000-007e-11ea-9f8f-4983facf0c1d.png)

复制 `Download URL` 下载链接 的内容，这个链接就是图片链接了。
![image](https://user-images.githubusercontent.com/25004510/68262786-3f3c8980-007f-11ea-8931-61404a718034.png)

同理，大文件 的 image 也可以放这里，避免图片占用小程序代码 2M 限制

如果是 Image 标签， src 也可以使用 云文件 id，即 File ID ，不过实测 云文件 id的访问方式没有缓存效果，第二次打开速度不及`Download URL` 的链接。

切记，不可贪杯，这里**只有 5G 的免费空间**，不过应该也够用了。

**Comment by Dekuuuu** [comment]
喆大师牛逼！【破音】🐶

**Comment by coppyC** [comment]
@Dekuuuu 小兄弟訁重了

**Comment by coppyC** [comment]
好吧，小程序的云服务现在已经开始收费了，再见
