### ISSUE TITLE
[2019-03-28] 解密 [] + {} === {} + []

### ISSUE THREAD

**Issue by coppyC** [coppyC/blog#4]
# 序

看到这个标题，你可能会想，这有什么好说的

这就和 `1 + 2 === 2 + 1` 一样正常

事实上，你是对的，因为 ` [] + {} === {} + [] ` 就是 `true`

但是，如果反过来呢 ` {} + [] === [] + {} `，你可能会思考一下，还是`true`

emmmmmm......你又对了，但如果结合一下这张图，问题看起来可能就没那么简单了
 
![image](https://user-images.githubusercontent.com/25004510/55149617-75c73300-5185-11e9-8fb6-a7cce4fb9812.png)

# 分析

一个是0，一个不是0，怎么就相等了？？？

要解释这张图，可能需要对js很深入的了解才行，我们一行一行来分析

## `[] + {} === 0`

是的，这段代码不会报错，可以运行

读过 《你不知道的js(中卷)》的人都知道，js 存在两种转换，一种是显式转换，一种是隐式转换

什么是显式转换？

像这样，把数字0换字符串'0'：String(0)  // '0'

或是这样，Boolean(1)  // true

比较明显的转换方式，都是显式转换

那什么是隐式转换？

像这种

0 + ''   // '0'

又或是 !!1 // true

不明显的转换

套用书中的一句话

> 只要你明白这是怎么回事，那它对你来说就是显式的，相反，如果你不知道String()可以用来做字符串强制类型转换，它对你来说可能是稳式的

那这里，就相当是这样

`String(Number([])) + String({}) === 0` 

那么 false 也就很好理解了

## `{} + [] === 0`

说了隐式转换，那我就直接说结论了，上面的式子会被这么解析

` {} (Number([]) === 0) `

没明白怎么回事？

前面的  `{} ` 会被解析成 es 6 的块作用域

不知道这是什么可以看 [这里](http://es6.ruanyifeng.com/#docs/let#%E5%9D%97%E7%BA%A7%E4%BD%9C%E7%94%A8%E5%9F%9F)

而后面就就被当成一个表达式了 

`+ []` 也是隐式转换，任何一个变量前面加上 `+`， 都会被强制转数字，（加法中的加号除外）

很多人可能都知道这个东西，但不知道为什么会转，很多资料也没有解析，

我曾经也思考过，后来给了这么个解释，这个不是被当 加号 解析，也是 正号，正负号的正号，所以就强转数字了

至于数组转换数字的规则，我就不多说了，毕竟知道了也没什么用，因为没人会这么编程，给自己埋炸弹， 反正一个空数组转数字会变成 0 就是了

所以最后 ` 0 === 0 `  // true

## ` [] + {} === {} + [] `

知道了上面的东西，这个就好说了

这是 ` {} + [] ` 中的 {} 在代码中间，不会被当 代码块 解析，左右走的都是字符串转换

结果相同

# 尾
如此一来，事件就结束了

等等，好像还没结束

回头看一看 `{} + [] === [] + {} `

## `{} + [] === [] + {} `

这个前面不是会被当 代码块 解析吗，怎么还是 true

这真的是很神奇，这里不会被当代码块解析，

我做了很多实验，最后在这几句上找到了灵感

`{} + []`  // 0
`{} + [] + 1` //   1
`{} + [] + 1 + '1' ` // '11'
`{} + [] + 1 + '1' + {}`  // "[object Object]11[object Object]"

可以看出，如果代码中有 {} 没有被当成代码块，而是对象，那么它就会把前面的 {} 也自做聪明解析成对象，而最后那个` +{} ` 显然没有办法解析成代码块

为什么说它神奇，因为我实在不能理解 它的自作聪明

我突然又来了灵感，如果在万恶的ie上试试看这个 `{} + [] === [] + {}` 会怎么样

答案是false

而其它的表达式和之前的一致

果然，`{} + [] === [] + {}` 会是true ，只是 chrome v8的神奇优化吗？

**Comment by xqdd** [comment]
花里胡哨，既不中看又不中用

**Comment by coppyC** [comment]
@XQDD 中不中用不重要，合理使用可以劝退前端学习
